project:
  type: website

website:
  title: "rtichoke blog"
  site-url: https://rtichoke-blog.netlify.app
  navbar:
    title: rtichoke blog
    right:
      - text: R examples
        href: posts.qmd
      - text: Python examples
        href: https://uriahf.github.io/rtichoke_blog_python
      - text: Talks
        href: talks.qmd
      - text: About Me
        href: about_me.qmd
      - icon: github
        href: https://github.com/uriahf
      - icon: twitter
        href: https://twitter.com/finkeluriah
      - icon: facebook
        href: https://www.facebook.com/groups/rforthemasses
      - icon: linkedin
        href: https://www.linkedin.com/in/uriah-finkel
      - icon: telegram
        href: https://t.me/as_if_uriah
      - icon: rss
        href: posts.xml  
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual